katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
    
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import addTask, check, deleteTask, show_todolist, addTask_ajax, show_json
from todolist.views import register #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from todolist.views import logout_user #sesuaikan dengan nama fungsi yang dibuat

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('json/', show_json, name='show_json'),
    path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat
    path('logout/', logout_user, name='logout'), #sesuaikan dengan nama fungsi yang dibuat
    path('create-task/', addTask, name='create-task'),
    path('check/<int:pk>/', check, name='check'),
    path('deleteTask/<int:pk>/', deleteTask, name='deleteTask'),
    path('json/', show_json, name='show_json'),
    path('addTask_ajax/', addTask_ajax, name='addTask_ajax'),
]

todolist/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoList(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import ToDoList

class create_form(forms.ModelForm):
    title = forms.CharField(label = "Title")
    description = forms.CharField(label = "Description")

todolist/views.py
# Create your views here.
import imp
from django.shortcuts import render
from todolist.models import ToDoList
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from todolist.models import ToDoList
from .forms import create_form
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist = ToDoList.objects.filter(user=request.user)
    context = {
        'todolist': data_todolist,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_json(request):
    data_todolist = ToDoList.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', data_todolist), content_type='application/json')


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response  
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def deleteTask(request, pk):
    item = ToDoList.objects.filter(pk=pk)
    item.delete()
    return redirect('todolist:show_todolist')

def addTask(request):

    if request.method == "POST":
        form = create_form(request.POST)
        # check whether it's valid:
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            ToDoList.objects.create(title = title, description = description, date = datetime.datetime.now(), user = request.user)
            return redirect('todolist:show_todolist')
    else: 
        form = create_form()

    context = {
        'form' : form,
        }
    return render(request, "create-task.html", context)

def check(request, pk):

    temp = ToDoList.objects.filter(user=request.user).get(pk=pk)
    if (temp.is_finished == False):
        temp.is_finished = True
    else :
        temp.is_finished = False
    temp.save()
    return redirect('todolist:show_todolist')


@login_required(login_url='/todolist/login/')
@csrf_exempt
def addTask_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        if title != "" or description != "":
            task = ToDoList.objects.create(title = title, description = description, date = datetime.datetime.now(), user = request.user)
            data = {
                'pk' : task.pk,
                'fields' : {
                    'title' : task.title,
                    'description' : task.description,
                    'is_finished' : task.is_finished,
                    'date' : task.date
                }
            }
            return JsonResponse(data)

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block meta %}
<title>Add New Task</title>
{% endblock meta %}

{% block content %}  
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<div class="m-5 d-flex flex-column justify-content-center align-items-center" >
    
    <div class="card">
        <div class="card-body">

            <h1 class="text-4xl font-semibold mb-4">Add New Task</h1>  

                <form method="POST" >  
                    {% csrf_token %}  
                    <table>  
                        {{ form.as_table }}  
                        <tr>  
                            <td></td>
                            <td><input class="btn btn-primary p-1 mx-auto my-auto" type="submit" name="submit" value="Tambah"/></td>  
                        </tr>  
                    </table>  
                </form>

            {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
            {% endif %}
    
        </div>
    </div>

</div>  

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<div class="m-5 d-flex flex-column justify-content-center align-items-center">
    
    <div class="card">
        <div class="card-body">

            <h1 class="text-4xl font-semibold mb-4">Login</h1>

            <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Username: </td>
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td>Password: </td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>

                    <tr>
                        <td></td>
                        <td><input class="btn btn-primary p-1 mx-auto my-auto" type="submit" value="Login"></td>
                    </tr>
                </table>
            </form>

            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}     
                
            Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>

        </div>
    </div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<div class="m-5 d-flex flex-column justify-content-center align-items-center">
    
    <div class="card">
        <div class="card-body">
            <h1 class="text-4xl font-semibold mb-4">Formulir Registrasi</h1> 


                <form method="POST" >  
                    {% csrf_token %}  
                    <table>  
                        {{ form.as_table }}  
                        <tr>  
                            <td></td>
                            <td><input class="btn btn-primary p-1 mx-auto my-auto" type="submit" name="submit" value="Daftar"/></td>  
                        </tr>  
                    </table>  
                </form>
            

                {% if messages %}  
                    <ul>   
                        {% for message in messages %}  
                            <li>{{ message }}</li>  
                            {% endfor %}  
                    </ul>   
                {% endif %}
        </div>
    </div>

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}
 <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">PBP Assignments</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" data-bs-toggle="modal" data-bs-target="#modaladd" href="#">Create New Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'todolist:logout' %}">Logout</a>
        </li>
      </ul>
      <span class="navbar-text">
        Logged in as {{ user.get_username }}
      </span>
    </div>
  </div>
</nav>

<head>

</head>

<body>

  <div class="m-5 d-flex flex-column justify-content-center align-items-center">
    <h1 class="text-4xl font-semibold mb-4"> {{ user.get_username }}'s To Do Lists</h1>
  </div>

  <form action="" method="POST" id="newTask">  
    {% csrf_token %}  
    <table>  
        <div class="modal fade" id="modaladd" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">Create New Task</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input class="form-control" type="text" id="title" name="title" placeholder="Title" aria-label="Title" aria-describedby="basic-addon1">
                    <br>
                    <input class="form-control" type="text" id="description" name="description" placeholder="Description" aria-label="Description" aria-describedby="basic-addon1">
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary" data-bs-dismiss="modal" id="tombolCreate">Create</button>
                </div>
              </div>
            </div>
          </div>
    </table>
  </form>

  <div class="row row-cols-md-3 mx-auto justify-content-center" id = "container">

  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script>
    $(document).ready(function(){
      console.log(1)
      $.get("/todolist/json/", function(data){
        console.log(2)
          for (let task = 0; task< data.length; task++) {
          $('#container').append(`<div class="col-auto mb-3">
          <div class="card border-secondary mx-auto">
            <div class="card">
            <h4 class="card-title">${data[task].fields.title}</h4>
            <p class="card-text">${data[task].fields.date}</p>
            ${!data[task].fields.is_finished ? '<p class="card-text">Status : Belum Selesai</p>' : '<p class="card-text">Status : Selesai</p>'}
            <p class="card-text">Quick Note : ${data[task].fields.description}</p>
            <a class="btn btn-primary p-1 mx-auto my-auto" href="/todolist/check/${data[task].pk}">Check</a>
            <a class="btn btn-danger p-1 mx-auto my-auto" href="/todolist/deleteTask/${data[task].pk}">Delete</a>
            </div>
          </div>
        </div>`)
          }
      });
    });

    $("#tombolCreate").click(function(){
      console.log(3)
      $.post( "/todolist/addTask_ajax/", {title : $("#title").val(), description : $("#description").val()}, function(data, status) {
        console.log(4)
        if (status == "success") {
          $('#container').append(`<div class="col-auto mb-3"
          <div class="col-sm-6 col-md-4 col-lg-3 p-1">
            <div class=" card">
            <h4 class="card-title">${data.title}</h4>
            <p class="card-text">${data.date}</p>
            ${!data.is_finished ? '<p class="card-text">Status : Belum Selesai</p>' : '<p class="card-text">Status : Selesai</p>'}
            <p class="card-text">Quick Note : ${data.description}</p>
            <a class="btn btn-primary" href="/todolist/check/${data.pk}">Check</a>
            <a class="btn btn-danger" href="/todolist/deleteTask/${data.pk}">Delete</a>
            </div>
          </div>
        </div>`)
          $('#title').val('')
          $('#description').val('')
          }
        })
      })

  </script>


</body>

 {% endblock content %}